version: "3.8"

services:
  bsc-geth:
    build:
      context: .
      dockerfile: Dockerfile.bsc
      args:
        GIT_SOURCE: https://github.com/binance-chain/bsc.git
        GIT_CHECKOUT_BRANCH: v1.2.10
    image: bsc-geth:docker-local
