services:
  bsc-geth:
    build:
      context: .
      dockerfile: Dockerfile.bsc
      args:
        GIT_SOURCE: https://github.com/NathanBSC/bsc
        GIT_CHECKOUT_BRANCH: BEP-341-produce-consecutive-blocks
    image: bsc-geth:docker-local
