services:
  bsc-geth:
    build:
      context: .
      dockerfile: Dockerfile.bsc
      args:
        GIT_SOURCE: https://github.com/bnb-chain/bsc
        GIT_CHECKOUT_BRANCH: v1.5.19
    image: bsc-geth:docker-local
