// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: relayer/chains/parlia/config/config.proto

package module

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ProverConfig struct {
	TrustLevelNumerator   uint64        `protobuf:"varint,1,opt,name=trust_level_numerator,json=trustLevelNumerator,proto3" json:"trust_level_numerator,omitempty"`
	TrustLevelDenominator uint64        `protobuf:"varint,2,opt,name=trust_level_denominator,json=trustLevelDenominator,proto3" json:"trust_level_denominator,omitempty"`
	TrustingPeriod        time.Duration `protobuf:"bytes,3,opt,name=trusting_period,json=trustingPeriod,proto3,stdduration" json:"trusting_period"`
}

func (m *ProverConfig) Reset()         { *m = ProverConfig{} }
func (m *ProverConfig) String() string { return proto.CompactTextString(m) }
func (*ProverConfig) ProtoMessage()    {}
func (*ProverConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_b9b2980c681540ea, []int{0}
}
func (m *ProverConfig) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProverConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProverConfig.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProverConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProverConfig.Merge(m, src)
}
func (m *ProverConfig) XXX_Size() int {
	return m.Size()
}
func (m *ProverConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProverConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProverConfig proto.InternalMessageInfo

func (m *ProverConfig) GetTrustLevelNumerator() uint64 {
	if m != nil {
		return m.TrustLevelNumerator
	}
	return 0
}

func (m *ProverConfig) GetTrustLevelDenominator() uint64 {
	if m != nil {
		return m.TrustLevelDenominator
	}
	return 0
}

func (m *ProverConfig) GetTrustingPeriod() time.Duration {
	if m != nil {
		return m.TrustingPeriod
	}
	return 0
}

func init() {
	proto.RegisterType((*ProverConfig)(nil), "relayer.chains.quorum.config.ProverConfig")
}

func init() {
	proto.RegisterFile("relayer/chains/parlia/config/config.proto", fileDescriptor_b9b2980c681540ea)
}

var fileDescriptor_b9b2980c681540ea = []byte{
	// 306 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0x41, 0x4a, 0x03, 0x31,
	0x14, 0x86, 0x27, 0x2a, 0x22, 0xa3, 0x28, 0x8c, 0x16, 0x6b, 0x91, 0xb4, 0xb8, 0xaa, 0x8b, 0x26,
	0x50, 0xc1, 0x03, 0xd4, 0x6e, 0x84, 0x22, 0xa5, 0x4b, 0x37, 0x25, 0x33, 0x93, 0xa6, 0x81, 0x4c,
	0x5e, 0x7d, 0x4d, 0x0a, 0xde, 0xc2, 0xa5, 0x47, 0xea, 0xb2, 0x4b, 0x57, 0x2a, 0xed, 0x45, 0xa4,
	0x99, 0x0e, 0x75, 0x95, 0x47, 0xbe, 0xff, 0x4b, 0x78, 0x7f, 0x7c, 0x8f, 0xd2, 0x88, 0x77, 0x89,
	0x3c, 0x9b, 0x0a, 0x6d, 0xe7, 0x7c, 0x26, 0xd0, 0x68, 0xc1, 0x33, 0xb0, 0x13, 0xad, 0x76, 0x07,
	0x9b, 0x21, 0x38, 0x48, 0x6e, 0x77, 0x51, 0x56, 0x46, 0xd9, 0x9b, 0x07, 0xf4, 0x05, 0x2b, 0x33,
	0x0d, 0xaa, 0x00, 0x94, 0x91, 0x3c, 0x64, 0x53, 0x3f, 0xe1, 0xb9, 0x47, 0xe1, 0x34, 0xd8, 0xd2,
	0x6e, 0x5c, 0x29, 0x50, 0x10, 0x46, 0xbe, 0x9d, 0xca, 0xdb, 0xbb, 0x25, 0x89, 0xcf, 0x86, 0x08,
	0x0b, 0x89, 0x4f, 0xe1, 0x99, 0xa4, 0x1b, 0xd7, 0x1c, 0xfa, 0xb9, 0x1b, 0x1b, 0xb9, 0x90, 0x66,
	0x6c, 0x7d, 0x21, 0x51, 0x38, 0xc0, 0x3a, 0x69, 0x91, 0xf6, 0xd1, 0xe8, 0x32, 0xc0, 0xc1, 0x96,
	0xbd, 0x54, 0x28, 0x79, 0x8c, 0xaf, 0xff, 0x3b, 0xb9, 0xb4, 0x50, 0x68, 0x1b, 0xac, 0x83, 0x60,
	0xd5, 0xf6, 0x56, 0x7f, 0x0f, 0x93, 0x41, 0x7c, 0x11, 0x80, 0xb6, 0x6a, 0x3c, 0x93, 0xa8, 0x21,
	0xaf, 0x1f, 0xb6, 0x48, 0xfb, 0xb4, 0x7b, 0xc3, 0xca, 0x65, 0x58, 0xb5, 0x0c, 0xeb, 0xef, 0x96,
	0xe9, 0x9d, 0x2c, 0xbf, 0x9b, 0xd1, 0xe7, 0x4f, 0x93, 0x8c, 0xce, 0x2b, 0x77, 0x18, 0xd4, 0xde,
	0xf3, 0x72, 0x4d, 0xc9, 0x6a, 0x4d, 0xc9, 0xef, 0x9a, 0x92, 0x8f, 0x0d, 0x8d, 0x56, 0x1b, 0x1a,
	0x7d, 0x6d, 0x68, 0xf4, 0xca, 0x95, 0x76, 0x53, 0x9f, 0xb2, 0x0c, 0x0a, 0x9e, 0x0b, 0x27, 0x42,
	0x7f, 0x46, 0xa4, 0x5c, 0xa7, 0x59, 0xa7, 0x2c, 0xbc, 0x13, 0xba, 0xe5, 0x05, 0xe4, 0xde, 0xc8,
	0xf4, 0x38, 0xfc, 0xfb, 0xf0, 0x17, 0x00, 0x00, 0xff, 0xff, 0xf2, 0x1d, 0xa8, 0x37, 0x9d, 0x01,
	0x00, 0x00,
}

func (m *ProverConfig) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProverConfig) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProverConfig) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	n1, err1 := github_com_gogo_protobuf_types.StdDurationMarshalTo(m.TrustingPeriod, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdDuration(m.TrustingPeriod):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintConfig(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x1a
	if m.TrustLevelDenominator != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.TrustLevelDenominator))
		i--
		dAtA[i] = 0x10
	}
	if m.TrustLevelNumerator != 0 {
		i = encodeVarintConfig(dAtA, i, uint64(m.TrustLevelNumerator))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintConfig(dAtA []byte, offset int, v uint64) int {
	offset -= sovConfig(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ProverConfig) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.TrustLevelNumerator != 0 {
		n += 1 + sovConfig(uint64(m.TrustLevelNumerator))
	}
	if m.TrustLevelDenominator != 0 {
		n += 1 + sovConfig(uint64(m.TrustLevelDenominator))
	}
	l = github_com_gogo_protobuf_types.SizeOfStdDuration(m.TrustingPeriod)
	n += 1 + l + sovConfig(uint64(l))
	return n
}

func sovConfig(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozConfig(x uint64) (n int) {
	return sovConfig(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ProverConfig) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProverConfig: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProverConfig: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustLevelNumerator", wireType)
			}
			m.TrustLevelNumerator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustLevelNumerator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustLevelDenominator", wireType)
			}
			m.TrustLevelDenominator = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TrustLevelDenominator |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustingPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthConfig
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthConfig
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_gogo_protobuf_types.StdDurationUnmarshal(&m.TrustingPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipConfig(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthConfig
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipConfig(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowConfig
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowConfig
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthConfig
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupConfig
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthConfig
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthConfig        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowConfig          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupConfig = fmt.Errorf("proto: unexpected end of group")
)
