// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: ibc/lightclients/parlia/v1/parlia.proto

package module

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	github_com_cosmos_gogoproto_types "github.com/cosmos/gogoproto/types"
	types "github.com/cosmos/ibc-go/v8/modules/core/02-client/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type ForkSpec struct {
	// Types that are valid to be assigned to HeightOrTimestamp:
	//	*ForkSpec_Height
	//	*ForkSpec_Timestamp
	HeightOrTimestamp         isForkSpec_HeightOrTimestamp `protobuf_oneof:"height_or_timestamp"`
	AdditionalHeaderItemCount uint64                       `protobuf:"varint,3,opt,name=additional_header_item_count,json=additionalHeaderItemCount,proto3" json:"additional_header_item_count,omitempty"`
	EpochLength               uint64                       `protobuf:"varint,4,opt,name=epoch_length,json=epochLength,proto3" json:"epoch_length,omitempty"`
}

func (m *ForkSpec) Reset()         { *m = ForkSpec{} }
func (m *ForkSpec) String() string { return proto.CompactTextString(m) }
func (*ForkSpec) ProtoMessage()    {}
func (*ForkSpec) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc631224085c6c85, []int{0}
}
func (m *ForkSpec) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ForkSpec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ForkSpec.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ForkSpec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ForkSpec.Merge(m, src)
}
func (m *ForkSpec) XXX_Size() int {
	return m.Size()
}
func (m *ForkSpec) XXX_DiscardUnknown() {
	xxx_messageInfo_ForkSpec.DiscardUnknown(m)
}

var xxx_messageInfo_ForkSpec proto.InternalMessageInfo

type isForkSpec_HeightOrTimestamp interface {
	isForkSpec_HeightOrTimestamp()
	MarshalTo([]byte) (int, error)
	Size() int
}

type ForkSpec_Height struct {
	Height uint64 `protobuf:"varint,1,opt,name=height,proto3,oneof" json:"height,omitempty"`
}
type ForkSpec_Timestamp struct {
	Timestamp uint64 `protobuf:"varint,2,opt,name=timestamp,proto3,oneof" json:"timestamp,omitempty"`
}

func (*ForkSpec_Height) isForkSpec_HeightOrTimestamp()    {}
func (*ForkSpec_Timestamp) isForkSpec_HeightOrTimestamp() {}

func (m *ForkSpec) GetHeightOrTimestamp() isForkSpec_HeightOrTimestamp {
	if m != nil {
		return m.HeightOrTimestamp
	}
	return nil
}

func (m *ForkSpec) GetHeight() uint64 {
	if x, ok := m.GetHeightOrTimestamp().(*ForkSpec_Height); ok {
		return x.Height
	}
	return 0
}

func (m *ForkSpec) GetTimestamp() uint64 {
	if x, ok := m.GetHeightOrTimestamp().(*ForkSpec_Timestamp); ok {
		return x.Timestamp
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*ForkSpec) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*ForkSpec_Height)(nil),
		(*ForkSpec_Timestamp)(nil),
	}
}

type ClientState struct {
	ChainId            uint64        `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	IbcStoreAddress    []byte        `protobuf:"bytes,2,opt,name=ibc_store_address,json=ibcStoreAddress,proto3" json:"ibc_store_address,omitempty"`
	IbcCommitmentsSlot []byte        `protobuf:"bytes,3,opt,name=ibc_commitments_slot,json=ibcCommitmentsSlot,proto3" json:"ibc_commitments_slot,omitempty"`
	LatestHeight       *types.Height `protobuf:"bytes,4,opt,name=latest_height,json=latestHeight,proto3" json:"latest_height,omitempty"`
	TrustingPeriod     time.Duration `protobuf:"bytes,5,opt,name=trusting_period,json=trustingPeriod,proto3,stdduration" json:"trusting_period"`
	MaxClockDrift      time.Duration `protobuf:"bytes,6,opt,name=max_clock_drift,json=maxClockDrift,proto3,stdduration" json:"max_clock_drift"`
	Frozen             bool          `protobuf:"varint,7,opt,name=frozen,proto3" json:"frozen,omitempty"`
	ForkSpecs          []*ForkSpec   `protobuf:"bytes,8,rep,name=fork_specs,json=forkSpecs,proto3" json:"fork_specs,omitempty"`
}

func (m *ClientState) Reset()         { *m = ClientState{} }
func (m *ClientState) String() string { return proto.CompactTextString(m) }
func (*ClientState) ProtoMessage()    {}
func (*ClientState) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc631224085c6c85, []int{1}
}
func (m *ClientState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClientState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClientState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClientState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientState.Merge(m, src)
}
func (m *ClientState) XXX_Size() int {
	return m.Size()
}
func (m *ClientState) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientState.DiscardUnknown(m)
}

var xxx_messageInfo_ClientState proto.InternalMessageInfo

type ETHHeader struct {
	Header []byte `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
}

func (m *ETHHeader) Reset()         { *m = ETHHeader{} }
func (m *ETHHeader) String() string { return proto.CompactTextString(m) }
func (*ETHHeader) ProtoMessage()    {}
func (*ETHHeader) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc631224085c6c85, []int{2}
}
func (m *ETHHeader) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ETHHeader) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ETHHeader.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ETHHeader) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ETHHeader.Merge(m, src)
}
func (m *ETHHeader) XXX_Size() int {
	return m.Size()
}
func (m *ETHHeader) XXX_DiscardUnknown() {
	xxx_messageInfo_ETHHeader.DiscardUnknown(m)
}

var xxx_messageInfo_ETHHeader proto.InternalMessageInfo

type Header struct {
	Headers            []*ETHHeader  `protobuf:"bytes,1,rep,name=headers,proto3" json:"headers,omitempty"`
	TrustedHeight      *types.Height `protobuf:"bytes,2,opt,name=trusted_height,json=trustedHeight,proto3" json:"trusted_height,omitempty"`
	CurrentValidators  [][]byte      `protobuf:"bytes,3,rep,name=current_validators,json=currentValidators,proto3" json:"current_validators,omitempty"`
	PreviousValidators [][]byte      `protobuf:"bytes,4,rep,name=previous_validators,json=previousValidators,proto3" json:"previous_validators,omitempty"`
	CurrentTurnLength  uint32        `protobuf:"varint,5,opt,name=current_turn_length,json=currentTurnLength,proto3" json:"current_turn_length,omitempty"`
	PreviousTurnLength uint32        `protobuf:"varint,6,opt,name=previous_turn_length,json=previousTurnLength,proto3" json:"previous_turn_length,omitempty"`
}

func (m *Header) Reset()         { *m = Header{} }
func (m *Header) String() string { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()    {}
func (*Header) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc631224085c6c85, []int{3}
}
func (m *Header) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Header) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Header.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Header) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Header.Merge(m, src)
}
func (m *Header) XXX_Size() int {
	return m.Size()
}
func (m *Header) XXX_DiscardUnknown() {
	xxx_messageInfo_Header.DiscardUnknown(m)
}

var xxx_messageInfo_Header proto.InternalMessageInfo

type ConsensusState struct {
	StateRoot              []byte `protobuf:"bytes,1,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	Timestamp              uint64 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	CurrentValidatorsHash  []byte `protobuf:"bytes,3,opt,name=current_validators_hash,json=currentValidatorsHash,proto3" json:"current_validators_hash,omitempty"`
	PreviousValidatorsHash []byte `protobuf:"bytes,4,opt,name=previous_validators_hash,json=previousValidatorsHash,proto3" json:"previous_validators_hash,omitempty"`
}

func (m *ConsensusState) Reset()         { *m = ConsensusState{} }
func (m *ConsensusState) String() string { return proto.CompactTextString(m) }
func (*ConsensusState) ProtoMessage()    {}
func (*ConsensusState) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc631224085c6c85, []int{4}
}
func (m *ConsensusState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ConsensusState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ConsensusState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ConsensusState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConsensusState.Merge(m, src)
}
func (m *ConsensusState) XXX_Size() int {
	return m.Size()
}
func (m *ConsensusState) XXX_DiscardUnknown() {
	xxx_messageInfo_ConsensusState.DiscardUnknown(m)
}

var xxx_messageInfo_ConsensusState proto.InternalMessageInfo

type Misbehaviour struct {
	ClientId string  `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Header_1 *Header `protobuf:"bytes,2,opt,name=header_1,json=header1,proto3" json:"header_1,omitempty"`
	Header_2 *Header `protobuf:"bytes,3,opt,name=header_2,json=header2,proto3" json:"header_2,omitempty"`
}

func (m *Misbehaviour) Reset()         { *m = Misbehaviour{} }
func (m *Misbehaviour) String() string { return proto.CompactTextString(m) }
func (*Misbehaviour) ProtoMessage()    {}
func (*Misbehaviour) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc631224085c6c85, []int{5}
}
func (m *Misbehaviour) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Misbehaviour) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Misbehaviour.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Misbehaviour) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Misbehaviour.Merge(m, src)
}
func (m *Misbehaviour) XXX_Size() int {
	return m.Size()
}
func (m *Misbehaviour) XXX_DiscardUnknown() {
	xxx_messageInfo_Misbehaviour.DiscardUnknown(m)
}

var xxx_messageInfo_Misbehaviour proto.InternalMessageInfo

type ProveState struct {
	AccountProof    []byte `protobuf:"bytes,1,opt,name=account_proof,json=accountProof,proto3" json:"account_proof,omitempty"`
	CommitmentProof []byte `protobuf:"bytes,2,opt,name=commitment_proof,json=commitmentProof,proto3" json:"commitment_proof,omitempty"`
}

func (m *ProveState) Reset()         { *m = ProveState{} }
func (m *ProveState) String() string { return proto.CompactTextString(m) }
func (*ProveState) ProtoMessage()    {}
func (*ProveState) Descriptor() ([]byte, []int) {
	return fileDescriptor_dc631224085c6c85, []int{6}
}
func (m *ProveState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ProveState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ProveState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ProveState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProveState.Merge(m, src)
}
func (m *ProveState) XXX_Size() int {
	return m.Size()
}
func (m *ProveState) XXX_DiscardUnknown() {
	xxx_messageInfo_ProveState.DiscardUnknown(m)
}

var xxx_messageInfo_ProveState proto.InternalMessageInfo

func init() {
	proto.RegisterType((*ForkSpec)(nil), "ibc.lightclients.parlia.v1.ForkSpec")
	proto.RegisterType((*ClientState)(nil), "ibc.lightclients.parlia.v1.ClientState")
	proto.RegisterType((*ETHHeader)(nil), "ibc.lightclients.parlia.v1.ETHHeader")
	proto.RegisterType((*Header)(nil), "ibc.lightclients.parlia.v1.Header")
	proto.RegisterType((*ConsensusState)(nil), "ibc.lightclients.parlia.v1.ConsensusState")
	proto.RegisterType((*Misbehaviour)(nil), "ibc.lightclients.parlia.v1.Misbehaviour")
	proto.RegisterType((*ProveState)(nil), "ibc.lightclients.parlia.v1.ProveState")
}

func init() {
	proto.RegisterFile("ibc/lightclients/parlia/v1/parlia.proto", fileDescriptor_dc631224085c6c85)
}

var fileDescriptor_dc631224085c6c85 = []byte{
	// 869 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6e, 0x1b, 0x45,
	0x14, 0xf6, 0xc6, 0xc1, 0xb1, 0x27, 0x76, 0x43, 0x27, 0x6d, 0xd9, 0x84, 0xb2, 0x09, 0x2e, 0x88,
	0x80, 0x94, 0x5d, 0x1c, 0x24, 0xc4, 0x0d, 0x8a, 0x1a, 0x17, 0xe4, 0x88, 0x56, 0x8a, 0x36, 0x15,
	0x17, 0x08, 0x69, 0x34, 0x3b, 0x3b, 0xf6, 0x8e, 0xb2, 0xbb, 0xb3, 0x9a, 0x99, 0xb5, 0x0a, 0x4f,
	0xc1, 0x25, 0xaf, 0xc0, 0x53, 0xf4, 0x36, 0x57, 0xa8, 0x97, 0x5c, 0xf1, 0x93, 0xbc, 0x08, 0x9a,
	0x9f, 0xb5, 0x8d, 0x0c, 0x05, 0xee, 0x66, 0xce, 0xf9, 0xbe, 0x73, 0x66, 0xce, 0x77, 0xce, 0x01,
	0x1f, 0xb0, 0x84, 0x44, 0x39, 0x9b, 0x65, 0x8a, 0xe4, 0x8c, 0x96, 0x4a, 0x46, 0x15, 0x16, 0x39,
	0xc3, 0xd1, 0x7c, 0xe4, 0x4e, 0x61, 0x25, 0xb8, 0xe2, 0x70, 0x9f, 0x25, 0x24, 0x5c, 0x05, 0x86,
	0xce, 0x3d, 0x1f, 0xed, 0xdf, 0x9b, 0xf1, 0x19, 0x37, 0xb0, 0x48, 0x9f, 0x2c, 0x63, 0xff, 0x40,
	0x87, 0x26, 0x5c, 0xd0, 0xc8, 0x32, 0x74, 0x48, 0x7b, 0x72, 0x80, 0x60, 0xc6, 0xf9, 0x2c, 0xa7,
	0x91, 0xb9, 0x25, 0xf5, 0x34, 0x4a, 0x6b, 0x81, 0x15, 0xe3, 0xa5, 0xf5, 0x0f, 0x5f, 0x7a, 0xa0,
	0xfb, 0x25, 0x17, 0x57, 0x97, 0x15, 0x25, 0xd0, 0x07, 0x9d, 0x8c, 0xea, 0xf4, 0xbe, 0x77, 0xe8,
	0x1d, 0x6d, 0x4e, 0x5a, 0xb1, 0xbb, 0xc3, 0x00, 0xf4, 0x14, 0x2b, 0xa8, 0x54, 0xb8, 0xa8, 0xfc,
	0x0d, 0xe7, 0x5c, 0x9a, 0xe0, 0x29, 0x78, 0x88, 0xd3, 0x94, 0xe9, 0xc0, 0x38, 0x47, 0x19, 0xc5,
	0x29, 0x15, 0x88, 0x29, 0x5a, 0x20, 0xc2, 0xeb, 0x52, 0xf9, 0x6d, 0x4d, 0x89, 0xf7, 0x96, 0x98,
	0x89, 0x81, 0x9c, 0x2b, 0x5a, 0x8c, 0x35, 0x00, 0xbe, 0x0b, 0xfa, 0xb4, 0xe2, 0x24, 0x43, 0x39,
	0x2d, 0x67, 0x2a, 0xf3, 0x37, 0x0d, 0x61, 0xdb, 0xd8, 0x9e, 0x1a, 0xd3, 0xd9, 0x7d, 0xb0, 0x6b,
	0x5f, 0x83, 0xb8, 0x40, 0x8b, 0xd4, 0xc3, 0x97, 0x6d, 0xb0, 0x3d, 0x36, 0x5f, 0xbe, 0x54, 0x58,
	0x51, 0xb8, 0x07, 0xba, 0x24, 0xc3, 0xac, 0x44, 0x2c, 0xb5, 0xdf, 0x88, 0xb7, 0xcc, 0xfd, 0x3c,
	0x85, 0x1f, 0x81, 0xbb, 0x2c, 0x21, 0x48, 0x2a, 0x2e, 0x28, 0xc2, 0x69, 0x2a, 0xa8, 0x94, 0xe6,
	0x37, 0xfd, 0x78, 0x87, 0x25, 0xe4, 0x52, 0xdb, 0x1f, 0x5b, 0x33, 0xfc, 0x18, 0xdc, 0xd3, 0x58,
	0xc2, 0x8b, 0x82, 0xa9, 0x42, 0x8b, 0x81, 0x64, 0xce, 0xed, 0x4f, 0xfa, 0x31, 0x64, 0x09, 0x19,
	0x2f, 0x5d, 0x97, 0x39, 0x57, 0xf0, 0x14, 0x0c, 0x72, 0xac, 0xa8, 0x54, 0xc8, 0x15, 0x51, 0xff,
	0x61, 0xfb, 0x64, 0x3f, 0xd4, 0xaa, 0x6a, 0x8d, 0x42, 0xa7, 0xcc, 0x7c, 0x14, 0x4e, 0x0c, 0x22,
	0xee, 0x5b, 0x82, 0xbd, 0xc1, 0xa7, 0x60, 0x47, 0x89, 0x5a, 0x2a, 0x56, 0xce, 0x50, 0x45, 0x05,
	0xe3, 0xa9, 0xff, 0x86, 0x09, 0xb1, 0x17, 0x5a, 0x15, 0xc3, 0x46, 0xc5, 0xf0, 0x89, 0x53, 0xf1,
	0xac, 0x7b, 0xfd, 0xeb, 0x41, 0xeb, 0xc7, 0xdf, 0x0e, 0xbc, 0xf8, 0x4e, 0xc3, 0xbd, 0x30, 0x54,
	0xf8, 0x15, 0xd8, 0x29, 0xf0, 0x0b, 0x44, 0x72, 0x4e, 0xae, 0x50, 0x2a, 0xd8, 0x54, 0xf9, 0x9d,
	0xff, 0x1e, 0x6d, 0x50, 0xe0, 0x17, 0x63, 0x4d, 0x7d, 0xa2, 0x99, 0xf0, 0x01, 0xe8, 0x4c, 0x05,
	0xff, 0x9e, 0x96, 0xfe, 0xd6, 0xa1, 0x77, 0xd4, 0x8d, 0xdd, 0x0d, 0x8e, 0x01, 0x98, 0x72, 0x71,
	0x85, 0x64, 0x45, 0x89, 0xf4, 0xbb, 0x87, 0xed, 0xa3, 0xed, 0x93, 0xf7, 0xc2, 0x7f, 0x6e, 0xe3,
	0xb0, 0xe9, 0xb5, 0xb8, 0x37, 0x75, 0x27, 0x39, 0x7c, 0x04, 0x7a, 0x5f, 0x3c, 0x9f, 0xd8, 0x8e,
	0xd0, 0x99, 0x6c, 0xfb, 0x18, 0xf1, 0xfa, 0xb1, 0xbb, 0x0d, 0x7f, 0xde, 0x00, 0x1d, 0x07, 0x39,
	0x05, 0x5b, 0xd6, 0x28, 0x7d, 0xcf, 0x64, 0x7c, 0xff, 0x75, 0x19, 0x17, 0xa1, 0xe3, 0x86, 0x05,
	0x1f, 0x03, 0x5b, 0x2c, 0x9a, 0x36, 0x52, 0x6d, 0xfc, 0xab, 0x54, 0x03, 0xc7, 0x70, 0x5a, 0x1d,
	0x03, 0x48, 0x6a, 0x21, 0x68, 0xa9, 0xd0, 0x1c, 0xe7, 0x2c, 0xc5, 0x8a, 0x0b, 0xe9, 0xb7, 0x0f,
	0xdb, 0x47, 0xfd, 0xf8, 0xae, 0xf3, 0x7c, 0xbd, 0x70, 0xc0, 0x08, 0xec, 0x56, 0x82, 0xce, 0x19,
	0xaf, 0xe5, 0x2a, 0x7e, 0xd3, 0xe0, 0x61, 0xe3, 0x5a, 0x21, 0x84, 0x60, 0xb7, 0x89, 0xaf, 0x6a,
	0x51, 0x36, 0x63, 0xa1, 0xfb, 0x61, 0xb0, 0x48, 0xf0, 0xbc, 0x16, 0xa5, 0x1d, 0x0e, 0xdd, 0xae,
	0x8b, 0x04, 0xab, 0x84, 0x8e, 0x21, 0x2c, 0x32, 0x2c, 0x19, 0x7a, 0xf2, 0xef, 0x8c, 0x79, 0x29,
	0x69, 0x29, 0x6b, 0x69, 0x47, 0xe7, 0x1d, 0x00, 0xa4, 0x3e, 0x20, 0xc1, 0xb9, 0x72, 0xf5, 0xef,
	0x19, 0x4b, 0xcc, 0xb9, 0x82, 0x0f, 0xd7, 0x96, 0xc0, 0xea, 0x0a, 0xf8, 0x14, 0xbc, 0xb5, 0x5e,
	0x11, 0x94, 0x61, 0x99, 0xb9, 0x99, 0xb9, 0xbf, 0x56, 0x96, 0x09, 0x96, 0x19, 0xfc, 0x0c, 0xf8,
	0x7f, 0x53, 0x1a, 0x4b, 0xdc, 0x34, 0xc4, 0x07, 0xeb, 0xf5, 0xd1, 0xcc, 0xe1, 0x4f, 0x1e, 0xe8,
	0x3f, 0x63, 0x32, 0xa1, 0x19, 0xd6, 0x6e, 0x01, 0xdf, 0x06, 0x3d, 0xab, 0x5b, 0x33, 0xfb, 0xbd,
	0xb8, 0x6b, 0x0d, 0xe7, 0x29, 0xfc, 0x1c, 0x74, 0xdd, 0x5e, 0x1a, 0x39, 0xb9, 0x87, 0xaf, 0x6b,
	0x9b, 0xbf, 0xf6, 0xcc, 0x68, 0x85, 0x7e, 0x62, 0xfe, 0xf3, 0xbf, 0xe8, 0x27, 0xc3, 0x6f, 0x01,
	0xb8, 0x10, 0x7c, 0x4e, 0x6d, 0xa1, 0x1f, 0x81, 0x01, 0x26, 0x66, 0x33, 0xa2, 0x4a, 0x70, 0x3e,
	0x75, 0xb5, 0xee, 0x3b, 0xe3, 0x85, 0xb6, 0xc1, 0x0f, 0xc1, 0x9b, 0xcb, 0xed, 0xe3, 0x70, 0x6e,
	0x59, 0x2d, 0xed, 0x06, 0x7a, 0xf6, 0xec, 0xfa, 0x8f, 0xa0, 0x75, 0x7d, 0x13, 0x78, 0xaf, 0x6e,
	0x02, 0xef, 0xf7, 0x9b, 0xc0, 0xfb, 0xe1, 0x36, 0x68, 0xbd, 0xba, 0x0d, 0x5a, 0xbf, 0xdc, 0x06,
	0xad, 0x6f, 0xa2, 0x19, 0x53, 0x59, 0x9d, 0x84, 0x84, 0x17, 0x51, 0x8a, 0x15, 0x36, 0xeb, 0x30,
	0xc7, 0x49, 0xc4, 0x12, 0x72, 0x6c, 0x9f, 0x7c, 0x2c, 0x68, 0x8e, 0xbf, 0x8b, 0x0a, 0x9e, 0xd6,
	0x39, 0x4d, 0x3a, 0x66, 0x33, 0x7c, 0xf2, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdc, 0x3a, 0x4e,
	0x76, 0xb9, 0x06, 0x00, 0x00,
}

func (m *ForkSpec) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ForkSpec) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ForkSpec) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EpochLength != 0 {
		i = encodeVarintParlia(dAtA, i, uint64(m.EpochLength))
		i--
		dAtA[i] = 0x20
	}
	if m.AdditionalHeaderItemCount != 0 {
		i = encodeVarintParlia(dAtA, i, uint64(m.AdditionalHeaderItemCount))
		i--
		dAtA[i] = 0x18
	}
	if m.HeightOrTimestamp != nil {
		{
			size := m.HeightOrTimestamp.Size()
			i -= size
			if _, err := m.HeightOrTimestamp.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
		}
	}
	return len(dAtA) - i, nil
}

func (m *ForkSpec_Height) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ForkSpec_Height) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintParlia(dAtA, i, uint64(m.Height))
	i--
	dAtA[i] = 0x8
	return len(dAtA) - i, nil
}
func (m *ForkSpec_Timestamp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ForkSpec_Timestamp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	i = encodeVarintParlia(dAtA, i, uint64(m.Timestamp))
	i--
	dAtA[i] = 0x10
	return len(dAtA) - i, nil
}
func (m *ClientState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClientState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClientState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ForkSpecs) > 0 {
		for iNdEx := len(m.ForkSpecs) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ForkSpecs[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParlia(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x42
		}
	}
	if m.Frozen {
		i--
		if m.Frozen {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	n1, err1 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.MaxClockDrift, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxClockDrift):])
	if err1 != nil {
		return 0, err1
	}
	i -= n1
	i = encodeVarintParlia(dAtA, i, uint64(n1))
	i--
	dAtA[i] = 0x32
	n2, err2 := github_com_cosmos_gogoproto_types.StdDurationMarshalTo(m.TrustingPeriod, dAtA[i-github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TrustingPeriod):])
	if err2 != nil {
		return 0, err2
	}
	i -= n2
	i = encodeVarintParlia(dAtA, i, uint64(n2))
	i--
	dAtA[i] = 0x2a
	if m.LatestHeight != nil {
		{
			size, err := m.LatestHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParlia(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.IbcCommitmentsSlot) > 0 {
		i -= len(m.IbcCommitmentsSlot)
		copy(dAtA[i:], m.IbcCommitmentsSlot)
		i = encodeVarintParlia(dAtA, i, uint64(len(m.IbcCommitmentsSlot)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.IbcStoreAddress) > 0 {
		i -= len(m.IbcStoreAddress)
		copy(dAtA[i:], m.IbcStoreAddress)
		i = encodeVarintParlia(dAtA, i, uint64(len(m.IbcStoreAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.ChainId != 0 {
		i = encodeVarintParlia(dAtA, i, uint64(m.ChainId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ETHHeader) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ETHHeader) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ETHHeader) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Header) > 0 {
		i -= len(m.Header)
		copy(dAtA[i:], m.Header)
		i = encodeVarintParlia(dAtA, i, uint64(len(m.Header)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Header) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Header) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Header) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PreviousTurnLength != 0 {
		i = encodeVarintParlia(dAtA, i, uint64(m.PreviousTurnLength))
		i--
		dAtA[i] = 0x30
	}
	if m.CurrentTurnLength != 0 {
		i = encodeVarintParlia(dAtA, i, uint64(m.CurrentTurnLength))
		i--
		dAtA[i] = 0x28
	}
	if len(m.PreviousValidators) > 0 {
		for iNdEx := len(m.PreviousValidators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.PreviousValidators[iNdEx])
			copy(dAtA[i:], m.PreviousValidators[iNdEx])
			i = encodeVarintParlia(dAtA, i, uint64(len(m.PreviousValidators[iNdEx])))
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.CurrentValidators) > 0 {
		for iNdEx := len(m.CurrentValidators) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.CurrentValidators[iNdEx])
			copy(dAtA[i:], m.CurrentValidators[iNdEx])
			i = encodeVarintParlia(dAtA, i, uint64(len(m.CurrentValidators[iNdEx])))
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.TrustedHeight != nil {
		{
			size, err := m.TrustedHeight.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParlia(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Headers) > 0 {
		for iNdEx := len(m.Headers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Headers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintParlia(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *ConsensusState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ConsensusState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ConsensusState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.PreviousValidatorsHash) > 0 {
		i -= len(m.PreviousValidatorsHash)
		copy(dAtA[i:], m.PreviousValidatorsHash)
		i = encodeVarintParlia(dAtA, i, uint64(len(m.PreviousValidatorsHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.CurrentValidatorsHash) > 0 {
		i -= len(m.CurrentValidatorsHash)
		copy(dAtA[i:], m.CurrentValidatorsHash)
		i = encodeVarintParlia(dAtA, i, uint64(len(m.CurrentValidatorsHash)))
		i--
		dAtA[i] = 0x1a
	}
	if m.Timestamp != 0 {
		i = encodeVarintParlia(dAtA, i, uint64(m.Timestamp))
		i--
		dAtA[i] = 0x10
	}
	if len(m.StateRoot) > 0 {
		i -= len(m.StateRoot)
		copy(dAtA[i:], m.StateRoot)
		i = encodeVarintParlia(dAtA, i, uint64(len(m.StateRoot)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *Misbehaviour) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Misbehaviour) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Misbehaviour) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Header_2 != nil {
		{
			size, err := m.Header_2.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParlia(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Header_1 != nil {
		{
			size, err := m.Header_1.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintParlia(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.ClientId) > 0 {
		i -= len(m.ClientId)
		copy(dAtA[i:], m.ClientId)
		i = encodeVarintParlia(dAtA, i, uint64(len(m.ClientId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *ProveState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ProveState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ProveState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CommitmentProof) > 0 {
		i -= len(m.CommitmentProof)
		copy(dAtA[i:], m.CommitmentProof)
		i = encodeVarintParlia(dAtA, i, uint64(len(m.CommitmentProof)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.AccountProof) > 0 {
		i -= len(m.AccountProof)
		copy(dAtA[i:], m.AccountProof)
		i = encodeVarintParlia(dAtA, i, uint64(len(m.AccountProof)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintParlia(dAtA []byte, offset int, v uint64) int {
	offset -= sovParlia(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *ForkSpec) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.HeightOrTimestamp != nil {
		n += m.HeightOrTimestamp.Size()
	}
	if m.AdditionalHeaderItemCount != 0 {
		n += 1 + sovParlia(uint64(m.AdditionalHeaderItemCount))
	}
	if m.EpochLength != 0 {
		n += 1 + sovParlia(uint64(m.EpochLength))
	}
	return n
}

func (m *ForkSpec_Height) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovParlia(uint64(m.Height))
	return n
}
func (m *ForkSpec_Timestamp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	n += 1 + sovParlia(uint64(m.Timestamp))
	return n
}
func (m *ClientState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ChainId != 0 {
		n += 1 + sovParlia(uint64(m.ChainId))
	}
	l = len(m.IbcStoreAddress)
	if l > 0 {
		n += 1 + l + sovParlia(uint64(l))
	}
	l = len(m.IbcCommitmentsSlot)
	if l > 0 {
		n += 1 + l + sovParlia(uint64(l))
	}
	if m.LatestHeight != nil {
		l = m.LatestHeight.Size()
		n += 1 + l + sovParlia(uint64(l))
	}
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.TrustingPeriod)
	n += 1 + l + sovParlia(uint64(l))
	l = github_com_cosmos_gogoproto_types.SizeOfStdDuration(m.MaxClockDrift)
	n += 1 + l + sovParlia(uint64(l))
	if m.Frozen {
		n += 2
	}
	if len(m.ForkSpecs) > 0 {
		for _, e := range m.ForkSpecs {
			l = e.Size()
			n += 1 + l + sovParlia(uint64(l))
		}
	}
	return n
}

func (m *ETHHeader) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Header)
	if l > 0 {
		n += 1 + l + sovParlia(uint64(l))
	}
	return n
}

func (m *Header) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Headers) > 0 {
		for _, e := range m.Headers {
			l = e.Size()
			n += 1 + l + sovParlia(uint64(l))
		}
	}
	if m.TrustedHeight != nil {
		l = m.TrustedHeight.Size()
		n += 1 + l + sovParlia(uint64(l))
	}
	if len(m.CurrentValidators) > 0 {
		for _, b := range m.CurrentValidators {
			l = len(b)
			n += 1 + l + sovParlia(uint64(l))
		}
	}
	if len(m.PreviousValidators) > 0 {
		for _, b := range m.PreviousValidators {
			l = len(b)
			n += 1 + l + sovParlia(uint64(l))
		}
	}
	if m.CurrentTurnLength != 0 {
		n += 1 + sovParlia(uint64(m.CurrentTurnLength))
	}
	if m.PreviousTurnLength != 0 {
		n += 1 + sovParlia(uint64(m.PreviousTurnLength))
	}
	return n
}

func (m *ConsensusState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.StateRoot)
	if l > 0 {
		n += 1 + l + sovParlia(uint64(l))
	}
	if m.Timestamp != 0 {
		n += 1 + sovParlia(uint64(m.Timestamp))
	}
	l = len(m.CurrentValidatorsHash)
	if l > 0 {
		n += 1 + l + sovParlia(uint64(l))
	}
	l = len(m.PreviousValidatorsHash)
	if l > 0 {
		n += 1 + l + sovParlia(uint64(l))
	}
	return n
}

func (m *Misbehaviour) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ClientId)
	if l > 0 {
		n += 1 + l + sovParlia(uint64(l))
	}
	if m.Header_1 != nil {
		l = m.Header_1.Size()
		n += 1 + l + sovParlia(uint64(l))
	}
	if m.Header_2 != nil {
		l = m.Header_2.Size()
		n += 1 + l + sovParlia(uint64(l))
	}
	return n
}

func (m *ProveState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccountProof)
	if l > 0 {
		n += 1 + l + sovParlia(uint64(l))
	}
	l = len(m.CommitmentProof)
	if l > 0 {
		n += 1 + l + sovParlia(uint64(l))
	}
	return n
}

func sovParlia(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozParlia(x uint64) (n int) {
	return sovParlia(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *ForkSpec) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParlia
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ForkSpec: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ForkSpec: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HeightOrTimestamp = &ForkSpec_Height{v}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.HeightOrTimestamp = &ForkSpec_Timestamp{v}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field AdditionalHeaderItemCount", wireType)
			}
			m.AdditionalHeaderItemCount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.AdditionalHeaderItemCount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EpochLength", wireType)
			}
			m.EpochLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EpochLength |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParlia(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParlia
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClientState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParlia
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClientState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClientState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ChainId", wireType)
			}
			m.ChainId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ChainId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcStoreAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcStoreAddress = append(m.IbcStoreAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.IbcStoreAddress == nil {
				m.IbcStoreAddress = []byte{}
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IbcCommitmentsSlot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IbcCommitmentsSlot = append(m.IbcCommitmentsSlot[:0], dAtA[iNdEx:postIndex]...)
			if m.IbcCommitmentsSlot == nil {
				m.IbcCommitmentsSlot = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LatestHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.LatestHeight == nil {
				m.LatestHeight = &types.Height{}
			}
			if err := m.LatestHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustingPeriod", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.TrustingPeriod, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaxClockDrift", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := github_com_cosmos_gogoproto_types.StdDurationUnmarshal(&m.MaxClockDrift, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Frozen", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Frozen = bool(v != 0)
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ForkSpecs", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ForkSpecs = append(m.ForkSpecs, &ForkSpec{})
			if err := m.ForkSpecs[len(m.ForkSpecs)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParlia(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParlia
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ETHHeader) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParlia
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ETHHeader: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ETHHeader: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Header = append(m.Header[:0], dAtA[iNdEx:postIndex]...)
			if m.Header == nil {
				m.Header = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParlia(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParlia
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Header) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParlia
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Header: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Header: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Headers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Headers = append(m.Headers, &ETHHeader{})
			if err := m.Headers[len(m.Headers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustedHeight", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.TrustedHeight == nil {
				m.TrustedHeight = &types.Height{}
			}
			if err := m.TrustedHeight.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentValidators", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentValidators = append(m.CurrentValidators, make([]byte, postIndex-iNdEx))
			copy(m.CurrentValidators[len(m.CurrentValidators)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousValidators", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviousValidators = append(m.PreviousValidators, make([]byte, postIndex-iNdEx))
			copy(m.PreviousValidators[len(m.PreviousValidators)-1], dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentTurnLength", wireType)
			}
			m.CurrentTurnLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CurrentTurnLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousTurnLength", wireType)
			}
			m.PreviousTurnLength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PreviousTurnLength |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipParlia(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParlia
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ConsensusState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParlia
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ConsensusState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ConsensusState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StateRoot", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StateRoot = append(m.StateRoot[:0], dAtA[iNdEx:postIndex]...)
			if m.StateRoot == nil {
				m.StateRoot = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Timestamp", wireType)
			}
			m.Timestamp = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Timestamp |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CurrentValidatorsHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CurrentValidatorsHash = append(m.CurrentValidatorsHash[:0], dAtA[iNdEx:postIndex]...)
			if m.CurrentValidatorsHash == nil {
				m.CurrentValidatorsHash = []byte{}
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PreviousValidatorsHash", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PreviousValidatorsHash = append(m.PreviousValidatorsHash[:0], dAtA[iNdEx:postIndex]...)
			if m.PreviousValidatorsHash == nil {
				m.PreviousValidatorsHash = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParlia(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParlia
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Misbehaviour) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParlia
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Misbehaviour: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Misbehaviour: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ClientId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header_1", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header_1 == nil {
				m.Header_1 = &Header{}
			}
			if err := m.Header_1.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Header_2", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Header_2 == nil {
				m.Header_2 = &Header{}
			}
			if err := m.Header_2.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParlia(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParlia
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ProveState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowParlia
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ProveState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ProveState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccountProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccountProof = append(m.AccountProof[:0], dAtA[iNdEx:postIndex]...)
			if m.AccountProof == nil {
				m.AccountProof = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CommitmentProof", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthParlia
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthParlia
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CommitmentProof = append(m.CommitmentProof[:0], dAtA[iNdEx:postIndex]...)
			if m.CommitmentProof == nil {
				m.CommitmentProof = []byte{}
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipParlia(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthParlia
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipParlia(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowParlia
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowParlia
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthParlia
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupParlia
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthParlia
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthParlia        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowParlia          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupParlia = fmt.Errorf("proto: unexpected end of group")
)
