name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unit-test:
    name: unit-test
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.58
          # still using the deprecated types in ibc-go v8
          args: --timeout=5m0s --disable staticcheck
      - name: test
        run: go test -v ./...
  e2e:
    name: e2e
    timeout-minutes: 45
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
      - name: test
        working-directory: e2e
        run: |
          make chain
          make contracts
          make relayer
          make test
